project:
  type: book

book:
  title: "BiomeXplore project"
  site-url: "https://dcosimber.github.io/BiomeXplore/"
  sidebar:
    logo: images/logo_biomexplore.png
    logo-alt: "BiomeXplore"
    logo-href: index.html
    search: true
  author:
    - name: Daniel Costas
      orcid: 0000-0003-4384-8469
      email: daniel.costas@iisgaliciasur.es
      affiliations:
        - name: Instituto de Investigación Sanitaria Galicia Sur (IISGS)
          city: Vigo
          state: Spain
          url: www.iisgs.es
        - name: Grupo de Microbiología e Infectología
          city: Vigo
          state: Spain
          url: https://biomexplore.eu/
  date: last-modified
  chapters:
    - index.qmd
    - chapters/01_workflow.qmd
    - chapters/02_meteor2.qmd
    - chapters/03_test.qmd
    - chapters/04_test.qmd
    - chapters/05_test.qmd
    - chapters/06_test.qmd
    - chapters/07_test.qmd

bibliography: references.bib

format:
  html:
    toc: true
    toc-depth: 3
    toc-location: right
    number-sections: true
    smooth-scroll: true
    anchor-sections: true
    css: styles.css
    theme:
      light: cosmo
      dark: darkly