project:
  type: book
  execute-dir: project

book:
  title: "BiomeXplore project"
  site-url: "https://dcosimber.github.io/BiomeXplore/"
  author:
    - name: Daniel Costas
      orcid: 0000-0003-4384-8469
      email: daniel.costas@iisgaliciasur.es
      affiliations:
        - name: Instituto de Investigación Sanitaria Galicia Sur (IISGS)
          city: Vigo
          state: Spain
          url: www.issgs.es
        - name: Grupo de Microbiología e Infectología
          city: Vigo
          state: Spain
          url: https://www.iisgaliciasur.es/areas-de-investigacion/enfermedades-inflamatorias-e-infecciosas-y-trastornos-inmunitarios/microbiologia-e-infectologia/

  date: last-modified
  chapters:
    - index.qmd
    - chapters/01_intro.qmd
    - chapters/02_methods_nfcore.qmd
    - chapters/03_results.qmd
    - chapters/03_qc_multiqc.qmd
    - chapters/04_alignment_quant.qmd
    - chapters/05_differential_expression.qmd

bibliography: references.bib

format:
  html:
    toc: true
    toc-location: left
    toc-depth: 3
    number-sections: true
    css: styles.css
    theme:
      light: cosmo
      dark: darkly
    theme-toggle: true
